---
- name: Subscribe to puppet repository on satellite.
  rhsm_repository:
    name: "{{ item }}"
    state: enabled
  loop: "{{ rabbitmq_repository_on_satellite }}"
  when: rabbitmq_repository_on_satellite is defined

- name: add erlang rpm key
  rpm_key:
    key: https://packages.erlang-solutions.com/rpm/erlang_solutions.asc
    state: present
  when: ansible_distribution != "RedHat"

- name: copy erlang repository
  copy:
    src: erlang.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644
  become: yes
  when: ansible_distribution != "RedHat"

- name: Install RabbitMQ dependencies
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - libselinux-python
    - erlang
    - socat

- name: install rabbitmq-server {{ rabbitmq_version }} (RedHat)
  yum:
    name: >
      {% if rabbitmq_repository_on_satellite is not defined %}
      https://dl.bintray.com/rabbitmq/all/rabbitmq-server/{{ rabbitmq_version }}/rabbitmq-server-{{ rabbitmq_version }}-1.el7.noarch.rpm
      {% else %}
      rabbitmq-server-{{ rabbitmq_version }}
      {% endif %}
    state: present

- name: enable rabbitmq-server to survive reboot
  service:
    name: rabbitmq-server
    enabled: yes
