---
- name: Install RabbitMQ on {{ ansible_distribution }}
  include_tasks: "install/{{ rabbitmq_install_task }}"
  when:
    - rabbitmq_install_enabled
    - ansible_distribution == 'RedHat' or ansible_distribution == 'OracleLinux'
  vars:
    rabbitmq_install_task: "{{ (ansible_os_family | lower) if (ansible_os_family == 'RedHat' or ansible_os_family == "OracleLinux") else (ansible_distribution | lower) }}.yml"
  tags: rabbitmq_install

- name: Tasks to configure RabbitMQ service
  include_tasks: config/main.yml
  tags: rabbitmq_configuration

- name: Install plugins tasks
  include_tasks: config/plugins.yml
  when: rabbitmq_manage_plugins
  tags: rabbitmq_plugins

- name: Configure cluster
  include_tasks: config/clustering.yml
  when: rabbitmq_clustering_enabled
  tags: rabbitmq_clustering

- name: Tasks to manage RabbitMQ Vhosts
  include_tasks: config/vhosts.yml
  when: rabbitmq_manage_vhosts
  with_items: "{{ rabbitmq_vhosts | dict2items }}"
  loop_control:
    loop_var: vhost_item
  tags: rabbitmq_vhosts
  run_once: true

- name: Tasks to manage RabbitMQ Queues
  include_tasks: config/queues.yml
  when: rabbitmq_manage_queues
  with_items: "{{ rabbitmq_queues | dict2items }}"
  loop_control:
    loop_var: queue_item
  tags: rabbitmq_queues
  run_once: true

- name: Tasks to manage RabbitMQ Exchanges
  include_tasks: config/exchanges.yml
  when: rabbitmq_manage_exchanges
  with_items: "{{ rabbitmq_exchanges | dict2items }}"
  loop_control:
    loop_var: exchange_item
  tags: rabbitmq_exchanges
  run_once: true

- name: Tasks to manage RabbitMQ Bindings
  include_tasks: config/bindings.yml
  when: rabbitmq_manage_bindings
  with_items: "{{ rabbitmq_bindings | dict2items }}"
  loop_control:
    loop_var: binding_item
  tags: rabbitmq_bindings
  run_once: true

- name: Tasks to manage RabbitMQ Users
  include_tasks: config/users.yml
  when: rabbitmq_manage_users
  tags: rabbitmq_users
  run_once: true

- name: Tasks to manage RabbitMQ Policies
  include_tasks: config/policies.yml
  tags: rabbitmq_policies
  run_once: true

- name: Configure new-relic rabbitmq infra agent
  include_tasks: config/monitoring-newrelic.yml
  when: rabbitmq_newrelic_agent_enabled
  tags: rabbitmq_monitoring
