---
- name: Enable plugins
  rabbitmq_plugin:
    names: "{{ rabbitmq_plugins | join(',') }}"
    state: enabled
    new_only: no # ensure that plugins that are not on list will be disabled.
  when:
    - rabbitmq_plugins | length > 0

- name: Force to correct enabled plugins permissions
  file:
    path: "{{ rabbitmq_enabled_plugins_file_path }}"
    owner: "{{ rabbitmq_owner }}"
    group: "{{ rabbitmq_group }}"
    mode: "0644"